# Generated by Django 5.2.8 on 2025-11-11 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'app_label': 'core_domain',
            },
        ),
        migrations.CreateModel(
            name="EvaluationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cv_match_rate", models.FloatField(blank=True, null=True)),
                ("cv_feedback", models.TextField(blank=True, null=True)),
                ("project_score", models.FloatField(blank=True, null=True)),
                ("project_feedback", models.TextField(blank=True, null=True)),
                ("overall_summary", models.TextField(blank=True, null=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_cv",
                        to="core_domain.uploadedfile",
                    ),
                ),
                (
                    "project_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_project_report",
                        to="core_domain.uploadedfile",
                    ),
                ),
            ],
            options={
                'app_label': 'core_domain',
            },
        ),
    ]
