# Generated by Django 5.2.8 on 2025-11-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            [
                "ALTER TABLE evaluations_uploadedfile RENAME TO core_domain_uploadedfile;",
                "ALTER TABLE evaluations_evaluationjob RENAME TO core_domain_evaluationjob;",
                "UPDATE django_content_type SET app_label = 'core_domain' WHERE app_label = 'evaluations' AND model IN ('uploadedfile', 'evaluationjob');"
            ],
            [
                "ALTER TABLE core_domain_uploadedfile RENAME TO evaluations_uploadedfile;",
                "ALTER TABLE core_domain_evaluationjob RENAME TO evaluations_evaluationjob;",
                "UPDATE django_content_type SET app_label = 'evaluations' WHERE app_label = 'core_domain' AND model IN ('uploadedfile', 'evaluationjob');"
            ]
        )
    ]
